version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - dinet

  sample-rest-api:
    image: node:12.10.0-alpine
    container_name: sampleRestApi
    command: >
      sh -c "
        npm install
        npm run start:dev
      "
    working_dir: /app
    volumes:
      - ../:/app
      - /app/node_modules/
    ports:
      - "8080:8080"
      - '8081:8081'
      - '50051:50051'
    env_file:
      - di.env
    links:
      - db
    depends_on:
      - db
    networks:
      - dinet

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: 
      - mysql:3306
    networks:
      - dinet

volumes:
  my-db:
networks:
  dinet:
